export default quotes = [
{id:1, quote:"Live as if you were to die tomorrow. Learn as if you were to live forever." , auth:"Mahatma Gandhi"},
{id:2,quote:"That which does not kill us makes us stronger." , auth:"Friedrich Nietzsche"},
{id:3,quote:"Be who you are and say what you feel, because those who mind don’t matter and those who matter don’t mind." , auth:"Bernard M. Baruch"},
{id:4,quote:"We must not allow other people’s limited perceptions to define us." , auth:"Virginia Satir"},
{id:5,quote:"Do what you can, with what you have, where you are." , auth:"Theodore Roosevelt"},
{id:6,quote:"Be yourself; everyone else is already taken." , auth:"Oscar Wilde"},
{id:7,quote:"This above all: to thine own self be true." , auth:"William Shakespeare"},
{id:8,quote:"If you cannot do great things, do small things in a great way." , auth:"Napoleon Hill"},
{id:9,quote:"If opportunity doesn’t knock, build a door." , auth:"Milton Berle"},
{id:10,quote:"Wise men speak because they have something to say; fools because they have to say something." , auth:"Plato"},
{id:11,quote:"Strive not to be a success, but rather to be of value." , auth:"Albert Einstein"},
{id:12,quote:"Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference." , auth:"Robert Frost"},
{id:13,quote:"Do not let what you cannot do interfere with what you can do." , auth:"John Wooden"},
{id:14,quote:"Whenever you find yourself on the side of the majority, it is time to pause and reflect." , auth:"Mark Twain"},
{id:15,quote:"I haven’t failed. I’ve just found 10,000 ways that won’t work." , auth:"Thomas Edison"},
{id:16,quote:"A journey of a thousand leagues begins beneath one’s feet." , auth:"Lao Tzu"},
{id:17,quote:"I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel." , auth:"Maya Angelou"},
{id:18,quote:"Either you run the day, or the day runs you." , auth:"Jim Rohn"},
{id:19,quote:"Life shrinks or expands in proportion to one’s courage." , auth:"Anais Nin"},
{id:20,quote:"You must be the change you wish to see in the world." , auth:"Mahatma Gandhi"},
{id:21,quote:"What you do speaks so loudly that I cannot hear what you say." , auth:"Ralph Waldo Emerson"},
{id:22,quote:"Believe and act as if it were impossible to fail." , auth:"Charles Kettering"},
{id:23,quote:"The difference between ordinary and extraordinary is that little extra." , auth:"Jimmy Johnson"},
{id:24,quote:"The best way to predict the future is to invent it." , auth:"Alan Kay"},
{id:25,quote:"If I am not for myself, who is for me? And if I am only for myself, what am I? And if not now, when?”,auth:"Rabbi Hillel"},
{id:26,quote:"Everything has beauty, but not everyone can see." , auth:"Confucius"},
{id:27,quote:"Believe you can and you’re halfway there." , auth:"Theodore Roosevelt"},
{id:28,quote:"How wonderful it is that nobody need wait a single moment before starting to improve the world." , auth:"Anne Frank"},
{id:29,quote:"Imagination is everything. It is the preview of life’s coming attractions." , auth:"Albert Einstein"},
{id:30,quote:"Change your thoughts and you change your world." , auth:"Norman Vincent"},
{id:31,quote:"Happiness is not something ready made. It comes from your own actions." , auth:"Dalai Lama"},
{id:32,quote:"Remember that happiness is a way of travel, not a destination." , auth:"Roy M. Goodman"},
{id:33,quote:"Too many of us are not living our dreams because we are living our fears." , auth:"Les Brown"},
{id:34,quote:"If you want to lift yourself up, lift up someone else." , auth:"Booker T. Washington"},
{id:35,quote:"You miss 100% of the shots you don’t take." , auth:"Wayne Gretzky"},
{id:36,quote:"It is never too late to be what you might have been." , auth:"George Eliot"},
{id:37,quote:"A person who never made a mistake never tried anything new." , auth:"Albert Einstein"},
{id:38,quote:"The person who says it cannot be done should not interrupt the person who is doing it." , auth:"Chinese Proverb"},
{id:39,quote:"Great minds discuss ideas; average minds discuss events; small minds discuss people." , auth:"Eleanor Roosevelt"},
{id:40,quote:"You only live once, but if you do it right, once is enough." , auth:"Mae West"},
{id:41,quote:"If you tell the truth, you don’t have to remember anything." , auth:"Mark Twain"},
{id:42,quote:"The only thing worse than being blind is having sight but no vision." , auth:"Helen Keller"},
{id:43,quote:"To live is the rarest thing in the world. Most people exist, that is all." , auth:"Oscar Wilde"},
{id:44,quote:"Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that." , auth:"Martin Luther King, Jr."},
{id:45,quote:"The only thing we have to fear is fear itself." , auth:"Franklin D. Roosevelt"},
{id:46,quote:"If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough." , auth:"Oprah Winfrey"},
{id:47,quote:"Remember no one can make you feel inferior without your consent." , auth:"Eleanor Roosevelt"},
{id:48,quote:"For every minute you are angry you lose sixty seconds of happiness." , auth:"Ralph Waldo Emerson"},
{id:49,quote:"Being deeply loved by someone gives you strength, while loving someone deeply gives you courage." , auth:"Lao Tzu"},
{id:50,quote:"There are two ways of spreading light: to be the candle or the mirror that reflects it." , auth:"Edith Wharton"},
{id:51,quote:"The road to success and the road to failure are almost exactly the same." , auth:"Colin R. Davis"},
{id:52,quote:"Motivation is a fire from within. If someone else tries to light that fire under you, chances are it will burn very briefly." , auth:"Stephen R. Covey"},
{id:53,quote:"In three words I can sum up everything I’ve learned about life: It goes on." , auth:"Robert Frost"},
{id:54,quote:"Self-reverence, self-knowledge, self control — these three alone lead to power." , auth:"Alfred, Lord Tennyson"},
{id:55,quote:"Though no one can go back and make a brand new start, anyone can start from now and make a brand new ending." , auth:"Carl Bard"},
{id:56,quote:"Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young. The greatest thing in life is to keep your mind young." , auth:"Henry Ford"},
{id:57,quote:"He who angers you conquers you." , auth:"Elizabeth Kenny"},
{id:58,quote:"Beauty, without expression, tires." , auth:"Ralph Waldo Emerson"},
{id:59,quote:"The secret of business is to know something that nobody else knows." , auth:"Aristotle Onassis"},
{id:60,quote:"The greatest discovery of all time is that a person can change his future by merely changing his attitude." , auth:"Oprah Winfrey"},
{id:61,quote:"We cannot always build the future of our youth, but we can build our youth for the future." , auth:"Franklin D. Roosevelt"},
{id:62,quote:"It takes courage to grow up and turn out to be who you really are." , auth:"E.E. Cummings"},
{id:63,quote:"In this world nothing can be said to be certain, except death and taxes." , auth:"Benjamin Franklin"},
{id:64,quote:"It is the mark of an educated mind to be able to entertain a thought without accepting it." , auth:"Aristotle"},
{id:65,quote:"A happy family is but an earlier heaven." , auth:"George Bernard Shaw"},
{id:66,quote:"Don’t walk in front of me, I may not follow. Don’t walk behind me, I may not lead. Walk beside me and be my friend." , auth:"Albert Camus"},
{id:67,quote:"Courage doesn’t always roar. Sometimes courage is the little voice at the end of the day that says ‘I’ll try again tomorrow.'”,auth:"Mary Anne Radmacher"},
{id:68,quote:"Education is like a double-edged sword. It may be turned to dangerous uses if it is not properly handled." , auth:"Wu Ting-Fang"},
{id:69,quote:"Walking with a friend in the dark is better than walking alone in the light." , auth:"Helen Keller"},
{id:70,quote:"Happiness is not a goal; it is a by-product." , auth:"Eleanor Roosevelt"},
{id:71,quote:"Always forgive your enemies; nothing annoys them so much." , auth:"Oscar Wilde"},
{id:72,quote:"The only true wisdom is knowing that you know nothing." , auth:"Socrates"},
{id:73,quote:"As a well-spent day brings happy sleep, so a life well spent brings happy death." , auth:"Leonardo da Vinci"},
{id:74,quote:"Courage is what it takes to stand up and speak. Courage is also what it takes to sit down and listen." , auth:"Winston Churchill"},
{id:75,quote:"Children are our most valuable resource." , auth:"Herbert Hoover"},
{id:76,quote:"Love is, above all else, the gift of oneself." , auth:"Jean Anouilh"},
{id:77,quote:"Music in the soul can be heard by the universe." , auth:"Lao Tzu"},
{id:78,quote:"Peace begins with a smile." , auth:"Mother Teresa"},
{id:79,quote:"Success is liking yourself, liking what you do, and liking how you do it." , auth:"Maya Angelou"},
{id:80,quote:"A friend is someone who knows all about you and still loves you." , auth:"Elbert Hubbard"},
{id:81,quote:"Never leave that till tomorrow which you can do today." , auth:"Benjamin Franklin"},
{id:82,quote:"If you don’t make mistakes, you’re not working on hard enough problems." , auth:"Frank Wilczek"},
{id:83,quote:"We must learn to live together as brothers or perish together as fools." , auth:"Martin Luther King, Jr."},
{id:84,quote:"Life is like a camera. Just focus on what’s important, capture the good times, develop from the negatives, and if things don’t work out, just take another shot." , auth:"Unknown"},
{id:85,quote:"When you judge another, you do not define them; you define yourself." , auth:"Wayne Dyer"},
{id:86,quote:"Opportunity is missed by most people because it is dressed in overalls and looks like work." , auth:"Thomas Edison"},
{id:87,quote:"Love me when I least deserve it, because that’s when I really need it." , auth:"Swedish Proverb"},
{id:88,quote:"The best and most beautiful things in the world cannot be seen or even touched. They must be felt with the heart." , auth:"Helen Keller"},
{id:89,quote:"If you want to test your memory, try to recall what you were worrying about one year ago today." , auth:"E. Joseph Cossman"},
{id:90,quote:"The real opportunity for success lies within the person and not in the job." , auth:"Zig Ziglar"},
{id:91,quote:"It takes a great deal of courage to stand up to your enemies, but even more to stand up to your friends." , auth:"J. K. Rowling"},
{id:92,quote:"Defeat is not bitter unless you swallow it." , auth:"Joe Clark"},
{id:93,quote:"A mind is like a parachute. It doesn’t work if it isn’t open." , auth:"Frank Zappa"},
{id:94,quote:"The man who removes a mountain begins by carrying away small stones." , auth:"Chinese Proverbs"},
{id:95,quote:"When you are totally at peace with yourself, nothing can shake you." , auth:"Deepam Chatterjee"},
{id:96,quote:"Be a first rate version of yourself, not a second rate version of someone else." , auth:"Judy Garland"},
{id:97,quote:"Your worth consists in what you are and not in what you have." , auth:"Thomas Edison"},
{id:98,quote:"Others can stop you temporarily – you are the only one who can do it permanently." , auth:"Zig Ziglar"},
{id:99,quote:"Life has no limitations, except the ones you make." , auth:"Les Brown"},
{id:100,quote:"Peace comes from within. Do not seek it without." , auth:"Muhammad Ali"},
{id:101,quote:"He who is not courageous enough to take risks will accomplish nothing in life." , auth:"Muhammad Ali"},
{id:102,quote:"Service to others is the rent you pay for your room here on earth." , auth:"Muhammad Ali"},
{id:103,quote:"A man who views the world the same at 50 as he did at 20 has wasted 30 years of his life." , auth:"Muhammad Ali"},
{id:104,quote:"It’s not bragging if you can back it up." , auth:"Muhammad Ali"},
{id:105,quote:"Failure is like free tuition." , auth:"Tomas Gorny"}
]